<?php include "common_upper.html" ?>

<?php
// sysstat_index.php:  修改为，直接通过sar文件名称生成对应的json，然后渲染到页面
//



$sarXX = $_GET['sarXX'];
$time_suffix = $_GET['time_suffix'];
//echo $sarXX.'</br>';

$sar_filename = $sarXX;
echo $sar_filename.'</br>';
echo '</br>';

define('SYSSTATDATAPATH','sysstat_datas/'.$time_suffix);
//echo SYSSTATDATAPATH.'</br>';
define('SYSSTATDATAFILENAME',$sar_filename);
//echo SYSSTATDATAFILENAME.'</br>';
define('JSONSTRUCTUREFILENAME','sysstat_datas/'.$time_suffix.'/'.$sar_filename.'.json');
//echo JSONSTRUCTUREFILENAME.'</br>';
define('NETWORKINTERFACELIST',serialize(array('lo','eth0')));


require('sysstat/generatestatdata.php');
require('sysstat/importstatfiledata.php');
require('sysstat/buildjsonstructure.php');



$generatestatdata = new generatestatdata();
$generatestatdata->execute();
?>


	<h1>SysStat Graph</h1>

	<div id="content"></div>

	<p>Generated by <a href="http://magnetikonline.com/sysstatgraph/">SysStat Graph Version 0.4</a></p>

	<script type="text/javascript">
	sysstatgraph.statdata = <?php echo((is_file(JSONSTRUCTUREFILENAME)) ? file_get_contents(JSONSTRUCTUREFILENAME) : '{}'); ?>;
	sysstatgraph.init();
	</script>



<?php include "common_bottom.html" ?>